---
title: "RWorksheet_Eusuya#1"
author: "Jonjeyl M. Eusuya"
date: "2024-09-29"
output: pdf_document
---

```{r}
# 1
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41)

# a. How many data points? - 34
# b.
length(age)

# 2
reciprocal <- 1/age
reciprocal

# 3
new_age <- c(age, 0, age)
new_age
# What happen to the new_age? -
# The new_age vector contains 2 age vector values seperated by 0

# 4
sorted_age <- sort(age)
sorted_age

# 5
min_age <- min(age)
min_age
max_age <- max(age)
max_age

# 6
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
# a. How many data points? - 12
# b. 
length(data)


# 7
doubled_data <- data * 2
doubled_data
# What happen to the data? -
# The values in data is doubled

# 8
# 8.1
integers <- seq(1:100)
integers
# 8.2
numbers <- seq(20, 60)
numbers
# 8.3
mean_numbers <- mean(numbers)
mean_numbers
# 8.4
sum_integers <- sum(integers[51:91])
sum_integers
# 8.5
integers_2 <- seq(1:1000)
# a. How many data points from 8.1 to 8.4? - 143
# b. 
length(integers) + length(numbers) + length(mean_numbers) + length(sum_integers)
# c. 
data_point <- integers_2[1:10]
max_data_point <- max(data_point)
max_data_point

# 9
filtered_integers <- Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
filtered_integers

# 10
backwards_integers <- sort(integers, decreasing = TRUE)
backwards_integers

# 11
numbers_2 <- 1:24
multiples <- numbers_2[numbers_2 %% 3 == 0 | numbers_2 %% 5 == 0]
multiples
sum_multiples <- sum(multiples)
sum_multiples
# a. How many data points from 10 to 11? - 111

# 12
# x <- {0 + x + 5 + }
# x
# Describe the output -
# There is no output because the syntax is incorrect

# 13
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
score1 <- score[2]
score1
score2<- score[3]
score2

# 14
a = c(1,2,NA,4,NA,6,7)
# a.
print(a,na.print="999")
# b. Describe the output. -
# The values NA from the vector a got replaced by 999 in the output
```

# 15
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```