---
title: "RWorksheet_Eusuya#3B"
author: "Jonjeyl M. Eusuya"
date: "2024-10-10"
output: pdf_document
---

# 1
# A 
```{r}

data <- data.frame(
  Respondents = c(1:20),
  Sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2),
  FathersOccupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1) ,
  PersonsAtHome =  c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),
  SiblingsAtSchool =  c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  TypesOfHouses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)
data
```
# B 
# The data has 20 rows and 6 columns
```{r}
summary(data)
```

# C 
```{r}
SiblingsAtSchool =  c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2)
mean(SiblingsAtSchool)
# No, the mean is 2.95
```
# D
```{r}
sub <- data[1:2, ]
sub
```
# E
```{r}
sub2 <- data[c(3, 5), c(2,4)]
sub2
```
# F
```{r}
types_houses <- data[, "TypesOfHouses"]
types_houses
```
# G
```{r}
males <- subset(data, Sex == 1 & FathersOccupation == 1)
males
```
# H
```{r}
females <- subset(data, Sex ==2 & SiblingsAtSchool >=5)
females
```
# 2
# A
```{r}
df = data.frame(Ints=integer(),
      Doubles=double(), Characters=character(),
      Logicals=logical(),
      Factors=factor(),
      stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
# It shows an empty data frame
```
# 3
# A
```{r}
HouseholdData <- read_xlsx("HouseholdData.csv")
HouseholdData
```
# B
```{r}
HouseholdData$Sex <- factor(HouseholdData$Sex, levels = c("Male", "Female"), labels = c(1,2))
HouseholdData
```
# C
```{r}
HouseholdData$TypesOfHouses <- factor(HouseholdData$TypesOfHouses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1, 2, 3))
HouseholdData
```
# D
```{r}
HouseholdData$FathersOccupation <- factor(HouseholdData$FathersOccupation, levels = c(1, 2, 3), labels = c("Farmer", "Driver", "Others"))
HouseholdData
```
# E
```{r}
females2 <- subset(HouseholdData, Sex==2 & FathersOccupation =="Driver")
females2
```
# F
```{r}
sub3 <- subset(HouseholdData, Respondents & SiblingsAtSchool >=  5)
sub3
```
# 4
# The graph shows the positive, negative and neutral sentiments of tweets per day from July 14 to 21, 2020.