---
title: "RWorksheet_Eusuya#4A"
author: "Jonjeyl M. Eusuya"
date: "2024-10-11"
output: "pdf_document"
---

# 1
# A
```{r}
data <- data.frame(
  ShoeSize = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
  
  Height = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
  
  Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
)
data
```
# B
```{r}
male_sub <- subset(data, Gender == "M", select = c(ShoeSize, Height))
female_sub <- subset(data, Gender == "F", select = c(ShoeSize, Height))
male_sub
female_sub
```
#C
```{r}
shoe_mean <- mean(data$ShoeSize)
height_mean <- mean(data$Height)
shoe_mean
height_mean
```
# D Is there a relationship between shoe size and height? Why?
# No, because the shoe size does not affect the height

# 2
```{r}
months_vector <- c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August","July","December","August","August","September","November","February",
"April")
factor_months_vector <- factor(months_vector)
factor_months_vector
```
# 3
```{r}
summary(months_vector)
summary(factor_months_vector)
```
# Interpret the results of both vectors. Are they both equally useful in this case?
# Yes, because they show the lenght, data type and contents of both vectors.

# 4
```{r}
Direction <- c("East","West","North")
Frequency <- c(1, 4, 3)

data2 <- cbind(Direction,Frequency)
data2
new_data2 <- factor(data2, levels = c("East","West","North"))
new_data2
```
# 5
```{r}
march <- read.csv("/cloud/project/RWorksheet_Eusuya#4A/import_march.csv")
march
```
# 6
```{r}
num <- as.numeric(readline(prompt="Enter a number from 1 to 50: "))

if(!is.na(num) && num == 20){
  print("TRUE")
}else {
  print("Invalid Input")
}
if(!is.na(num) && num>=1 && num<=50){
  num
}else{
  print("The number selected is beyond the range 1 to 50")
}
```
# 7
```{r}
price <- as.numeric(readline(prompt="Enter Price: "))
min_bills <- function(price) {
  bills_used <- 0
  
  if (!is.na(price) && price >= 1000) {
    bills_used <- bills_used + price %/% 1000
    price <- price %% 1000
  }
  if (!is.na(price) && price >= 500) {
    bills_used <- bills_used + price %/% 500
    price <- price %% 500
  }
  if (!is.na(price) && price >= 200) {
    bills_used <- bills_used + price %/% 200
    price <- price %% 200
  }
  if (!is.na(price) && price >= 100) {
    bills_used <- bills_used + price %/% 100
    price <- price %% 100
  }
  if (!is.na(price) && price >= 50) {
    bills_used <- bills_used + price %/% 50
    price <- price %% 50
  }
  return(bills_used)
}
min_bills(price)
```
# 8
# A
```{r}
data <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
data
```
# B
```{r}
avg_scores <- rowSums(data[,-1]) / (ncol(data) - 1)

if (any(avg_scores > 90)) {
  high_avg_names <- data$Name[avg_scores > 90]
  high_avg_scores <- avg_scores[avg_scores > 90]
  cat(paste(high_avg_names, "'s average grade this semester is ", high_avg_scores, ".\n", sep = ""))
} else {
  cat("No student's average grade is over 90.\n")
}
```
# C
```{r}
test_averages <- colSums(data[,-1]) / nrow(data)

if (any(test_averages < 80)) {
  difficult_tests <- which(test_averages < 80)
  cat(paste("The", difficult_tests, "th test was difficult.\n"))
} else {
  cat("All tests had average scores of 80 or above.\n")
}
```
# D
```{r}
highest_scores <- apply(data[,-1], 1, function(x) sort(x, decreasing = TRUE)[1])

if (any(highest_scores > 90)) {
  high_score_names <- data$Name[highest_scores > 90]
  high_scores <- highest_scores[highest_scores > 90]
  cat(paste(high_score_names, "'s highest grade this semester is ", high_scores, ".\n"))
} else {
  cat("No student's highest grade exceeded 90.\n")
}
```





