---
title: "RWorksheet_Eusuya#3A"
author: "Jonjeyl M. Eusuya"
date: "2024-10-10"
output: pdf_document
---

# Vectors
# 1 
```{r}
LETTERS
letters
```
# A
```{r}
First_11 <- LETTERS[1:11]
First_11
```
# B
```{r}
odd <- LETTERS[seq(1, length(LETTERS), 2) ]
odd
```
# C
```{r}
vowels <- c("A", "E", "I", "O", "U")
filtered <- LETTERS[LETTERS %in% vowels]
filtered
```
# D
```{r}
last_5 <- letters[22:26]
last_5
```
# E
```{r}
middle <- letters[14:24]
middle
```
# 2
# A
```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```
# B
```{r}
temp <- c(42, 39, 34, 34, 30, 27)
temp
```
# C
```{r}
places <- data.frame(city, temp)
places
```
# D
```{r}
names(places) <- c("City", "Temperature")
```
# E
```{r}
str(places)
# The output shows the content of the data frame and the data types of each vector
```
# F
```{r}
places[3, ]
places[4, ]
```
# G
```{r}
places[1, ]
places[6, ]
```
# Matrices
# 2
# A
```{r}
matrix_a <- matrix(c(1,2,3,4,5,6,7,8,11,12,13,14), ncol = 4, nrow = 3)
matrix_a
```
# B
```{r}
multiply <- matrix_a * 2
multiply
```
# C
```{r}
multiply[2, ]
```
# D
```{r}
multiply[1:2, 3:4]
```
# E
```{r}
multiply[3, 2:3]
```
# F
```{r}
multiply[, 4]
```
# G
```{r}
rownames(multiply) <- c("isa", "dalawa", "tatlo")
colnames(multiply) <- c("uno", "dos", "tres", "quatro")
multiply
```
# H
```{r}
dim(matrix_a) <- c(6, 2)
matrix_a
```
# Arrays
# 3
```{r}
array_A <- array(c(1:3,6:9,0,3:5,1))
array_A
repeat2 <- rep(array_A, 2)
repeat2
array_3D <- array(repeat2, dim = c(2, 4, 3))
array_3D
```
# B
```{r}
dim(array_3D)
```
# C
```{r}
row_names <- c("a", "b")
col_names <- c("A", "B", "C", "D")
dim_names <- list(row_names, col_names, c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
named_array <- array(repeat2, dim = c(2, 4, 3), dimnames = dim_names)
named_array
```


